import type { Metadata } from "next";
import { Geist } from "next/font/google";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Monaspace Radon (Nerd Font patched): the hand-drawn-styled mono face used
 * everywhere via `font-mono`. The bold file covers 600-700 so Tailwind's
 * `font-semibold` picks it up rather than synthesising a weight.
 */
const radonMono = localFont({
  variable: "--font-radon",
  src: [
    {
      path: "./fonts/MonaspiceRnNerdFontMono-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/MonaspiceRnNerdFontMono-Bold.woff2",
      weight: "600 700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${radonMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
